# TCL File Generated by Component Editor 17.0
# Tue Feb 20 17:24:22 EST 2018
# DO NOT MODIFY


# 
# quad_hex_decode "Quad 7-segment Hex Decoder" v1.0
#  2018.02.20.17:24:22
# Takes the written 16-bit word and displays it as four hex digits
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module quad_hex_decode
# 
set_module_property DESCRIPTION "Takes the written 16-bit word and displays it as four hex digits"
set_module_property NAME quad_hex_decode
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Quad 7-segment Hex Decoder"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL quad_hex_decode
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file quad_hex_decode.sv SYSTEM_VERILOG PATH quad_hex_decode.sv TOP_LEVEL_FILE
add_fileset_file hex_decode.sv SYSTEM_VERILOG PATH hex_decode.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point hex0
# 
add_interface hex0 conduit end
set_interface_property hex0 associatedClock clock
set_interface_property hex0 associatedReset ""
set_interface_property hex0 ENABLED true
set_interface_property hex0 EXPORT_OF ""
set_interface_property hex0 PORT_NAME_MAP ""
set_interface_property hex0 CMSIS_SVD_VARIABLES ""
set_interface_property hex0 SVD_ADDRESS_GROUP ""

add_interface_port hex0 HEX0 export Output 7


# 
# connection point hex1
# 
add_interface hex1 conduit end
set_interface_property hex1 associatedClock clock
set_interface_property hex1 associatedReset ""
set_interface_property hex1 ENABLED true
set_interface_property hex1 EXPORT_OF ""
set_interface_property hex1 PORT_NAME_MAP ""
set_interface_property hex1 CMSIS_SVD_VARIABLES ""
set_interface_property hex1 SVD_ADDRESS_GROUP ""

add_interface_port hex1 HEX1 export Output 7


# 
# connection point hex2
# 
add_interface hex2 conduit end
set_interface_property hex2 associatedClock clock
set_interface_property hex2 associatedReset ""
set_interface_property hex2 ENABLED true
set_interface_property hex2 EXPORT_OF ""
set_interface_property hex2 PORT_NAME_MAP ""
set_interface_property hex2 CMSIS_SVD_VARIABLES ""
set_interface_property hex2 SVD_ADDRESS_GROUP ""

add_interface_port hex2 HEX2 export Output 7


# 
# connection point hex3
# 
add_interface hex3 conduit end
set_interface_property hex3 associatedClock clock
set_interface_property hex3 associatedReset ""
set_interface_property hex3 ENABLED true
set_interface_property hex3 EXPORT_OF ""
set_interface_property hex3 PORT_NAME_MAP ""
set_interface_property hex3 CMSIS_SVD_VARIABLES ""
set_interface_property hex3 SVD_ADDRESS_GROUP ""

add_interface_port hex3 HEX3 export Output 7


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 16
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

